### PR TITLE
Create CI for PR.

### PR DESCRIPTION
**Pull request by edwardskrod**

### CODE REVIEW

**Comment by rfernand2** [comment]
Sorry to reply-all, but I keep getting automatically subscribed to all these different Microsoft Github projects.  Can you please remove me automatically being subscribed to projects that I have nothing to do with?

Thanks,

Roland

**Comment by jborsecnik** [comment]
Roland, you can ask the repo admin to fix this. They control such.

-jborsecnik

**Comment by 035** [comment]
I think this issue is probably affecting many people given the count of people watching this repo: ***@***.***

This has been an issue for many years and a similar issue was addressed at one point here: https://github.com/Microsoft/linguisticreview/issues/427#issuecomment-312336776

You could also try reaching out to ***@***.******@***.***> to see if there is any better solution other than having to manually change our GitHub notification settings.

**Comment by 035** [comment]
See also https://github.com/microsoft/southpaw/issues/333. I wish there was a better resolution to this other than expecting everyone to manually unwatch every repo.

**Pull request closed without merging**
